<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

final class ChannelType extends Enum
{
    const CHANNEL_FACEBOOK = 'facebook';
    const CHANNEL_YOUTUBE = 'youtube';
    const CHANNEL_INSTAGRAM = 'instagram';
    const CHANNEL_TWITTER = 'twitter';
    const CHANNEL_VLIVE = 'vlive';
    const CHANNEL_NEWS = 'news';

    public static function getDescription($value): string
    {
        switch ($value) {
            case self::CHANNEL_FACEBOOK :
                return '페이스북';
            case self::CHANNEL_YOUTUBE :
                return '유튜브';
            case self::CHANNEL_INSTAGRAM :
                return '인스타그램';
            case self::CHANNEL_TWITTER :
                return '트위터';
            case self::CHANNEL_VLIVE :
                return '브이라이브';
            case self::CHANNEL_NEWS :
                return '뉴스';
        }
        return parent::getDescription($value); // TODO: Change the autogenerated stub
    }
}
