<?php

namespace App\Enums;

use BenSampo\Enum\Enum;


final class UserSnsType extends Enum
{
    const SNS_NORMAL = 'normal';
    const SNS_FACEBOOK = 'facebook';
    const SNS_GOOGLE = 'google';
    const SNS_WECHAT = 'kakao';
    const SNS_LINE = 'line';
    const SNS_KAKAO = 'wechat';

    public static function getDescription($value): string
    {
        switch ($value) {
            case self::SNS_NORMAL :
                return "일반";
            case self::SNS_FACEBOOK :
                return '페이스북';
            case self::SNS_GOOGLE :
                return '구글';
            case self::SNS_WECHAT :
                return '위챗';
            case self::SNS_KAKAO :
                return '카카오';
            case self::SNS_LINE :
                return '라인';
        }

        return parent::getDescription($value); // TODO: Change the autogenerated stub
    }
}
