<?php

namespace App\Enums;

use BenSampo\Enum\Enum;

final class UserItemType extends Enum
{
    const BOARD_USE = 'B';
    const SIGN_UP_ADD = 'S';
    const DAILY_LOGIN_ADD = 'D';
    const FRIEND_INVITE_ADD = 'F';
    const BIRTH_DAY_ADD = 'BD';

    public static function getDescription($value): string
    {
        switch ($value) {
            case self::BOARD_USE :
                return "게시물 아이템 사용";
            case self::SIGN_UP_ADD :
                return '회원가입 아이템 충전';
            case self::DAILY_LOGIN_ADD :
                return '매일 출석 보상';
            case self::FRIEND_INVITE_ADD :
                return '친구 초대 보상';
            case self::BIRTH_DAY_ADD :
                return '유저 생일 보상';
        }


        return parent::getDescription($value); // TODO: Change the autogenerated stub
    }
}
